# Generated by Django 4.0.3 on 2022-04-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Networks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
