# Generated by Django 4.0.3 on 2022-04-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Networks', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
